XXX line endings, .gitattributes, etc

diff --git a/buildstuff/sed-substitute b/buildstuff/sed-substitute
--- a/buildstuff/sed-substitute
+++ b/buildstuff/sed-substitute
@@ -45,21 +45,30 @@ case "$outname" in
 	;;
 esac
 
-tmpname="$outname.tmp.$$"
+tmqname="$outname.tmq.$$"
 
-
-${SED-sed} -e "s|^\(.*\)[@]configure_input[@]|\1$outname.  Generated from $inname by configure.ac.\n\1!!!!!!! DO NOT MODIFY THIS FILE !!!!!!!!\n\1EDIT $inname INSTEAD AND RE-RUN autoreconf.|g" "$@" < "$inname" > "$tmpname" || {
+${SED-sed} -e "s|^\(.*\)[@]configure_input[@]|\1$outname.  Generated from $inname by configure.ac.\n\1!!!!!!! DO NOT MODIFY THIS FILE !!!!!!!!\n\1EDIT $inname INSTEAD AND RE-RUN autoreconf.|g" "$@" < "$inname" > "$tmqname" || {
     s="$?"
-    echo "$prog: Error running sed, exit code $s."
-    rm -f "$tmpname"
+    echo "$prog: Error running sed, exit code $s." >&2
+    rm -f "$tmqname"
     exit 2
 }
 
-if grep '[@][A-Za-z0-9_-]\{1,\}@' "$tmpname" >&2; then
+if grep '[@][A-Za-z0-9_-]\{1,\}@' "$tmqname" >&2; then
     echo "$prog: Unsubstituted values found while substituting $inname" >&2
-    rm -f "$tmpname"
+    rm -f "$tmqname"
     exit 2
 fi
+
+tmpname="$outname.tmp.$$"
+
+${TR-tr} -d '\015' < "$tmqname" > "$tmpname" || {
+    s="$?"
+    echo "$prog: Error running tr, exit code $s" >&2
+    rm -f "$tmqname"
+    exit 2
+}
+rm -f "$tmqname"
 
 if test -f "$outname"; then
     if ${CMP-cmp} "$outname" "$tmpname" > /dev/null; then
diff --git a/buildstuff/sed-update-source-file b/buildstuff/sed-update-source-file
--- a/buildstuff/sed-update-source-file
+++ b/buildstuff/sed-update-source-file
@@ -23,14 +23,22 @@ test -f "$fname" || {
 }
 
 tname="$fname.tmp.$$"
+qname="$fname.tmq.$$"
 
-
-${SED-sed} "$@" < "$fname" > "$tname" || {
+${SED-sed} "$@" < "$fname" > "$qname" || {
     s="$?"
-    echo "$prog: Error running sed, exit code $s." >&2
-    rm -f "$tname"
+    echo "$prog: Error running sed, exit code $s" >&2
+    rm -f "$qname"
     exit 2
 }
+
+${TR-tr} -d '\015' < "$qname" > "$tname" || {
+    s="$?"
+    echo "$prog: Error running tr, exit code $s" >&2
+    rm -f "$qname" "$tname"
+    exit 2
+}
+rm -f "$qname"
 
 test -s "$tname" || {
     echo "$prog: sed has produced an empty file" >&2
